name: Update Spotify Playing

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install axios dotenv

      - name: Update README
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        run: |
          node <<EOF
          const axios = require("axios");
          require('dotenv').config();

          async function getAccessToken() {
            const resp = await axios.post('https://accounts.spotify.com/api/token',
              new URLSearchParams({
                grant_type: 'refresh_token',
                refresh_token: process.env.SPOTIFY_REFRESH_TOKEN
              }),
              {
                headers: {
                  'Authorization': 'Basic ' + Buffer.from(process.env.SPOTIFY_CLIENT_ID + ':' + process.env.SPOTIFY_CLIENT_SECRET).toString('base64'),
                  'Content-Type': 'application/x-www-form-urlencoded'
                }
              });
            return resp.data.access_token;
          }

          async function getCurrentlyPlaying(token) {
            try {
              const resp = await axios.get('https://api.spotify.com/v1/me/player/currently-playing', {
                headers: { 'Authorization': 'Bearer ' + token }
              });

              if (resp.status === 204) return "Not playing";

              const song = resp.data.item;
              return `${song.name} — ${song.artists.map(a => a.name).join(', ')}`;
            } catch (err) {
              return "Nothing playing";
            }
          }

          (async () => {
            const token = await getAccessToken();
            const song = await getCurrentlyPlaying(token);
            const fs = require('fs');
            const readme = fs.readFileSync('README.md', 'utf8');
            const updated = readme.replace(/🎧 Now Playing: .*/, `🎧 Now Playing: ${song}`);
            fs.writeFileSync('README.md', updated);
          })();
          EOF
